### ISSUE TITLE
Some screens reach out to servers that no longer exist

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/b-step#10]
like forums, manual download, etc...

I have a couple of original very large tar.gz files from the first download which may contain some of these assets.

**Comment by haenkel** [comment]
I'll do some quick changes here, github/discord etc. instead of forum and mail-support.

I don't understand yet what the offline manual in combo with
"your friend the questionmark" is supposed to do exactly,
but that can be a step 2

btw @baconpaul do we still need this one?
```
case USE_VST_INSTEAD_OF_AU:
    return CharPair("YOU ARE USING THE B-STEP AUDIO UNIT!",
                    "If your host support VST's, then you should use the VST version instead "
                    "of the AudioUnit!\nIf you are using a host like Logic please read: "
                    "http://forum.monoplugs.com/logic");
```

**Comment by baconpaul** [comment]
I had no problem running latest as a midi fx in logic 10.7 and another user got it running macos 10.14 Logic 10.6. I do not think we need that (although in the past midi fx in logic were wierd and so I can imagine what it used to say)
