### ISSUE TITLE
go to c++ standard types for ints etc as opposed to juce types

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/b-step#11]
right now code is littered with `uint8` which is actually `juce::uint8` and we are `using namespace juce`

we should move those to the `<cstdint>` types like `uint8_t`

**Comment by falkTX** [comment]
what do those have to do with c++17? `uint8_t` is a thing even in C++98 and C89

**Comment by baconpaul** [comment]
"As opposed to juce types since we are now on C++ 17"

but they were in the standard from C++11 with a header. But I should have said "go to c++ standard types" instead. Thank you.

**Comment by baconpaul** [comment]
I have edited the subject. Would you like to make the change? :)

**Comment by falkTX** [comment]
I mean, just wanted to know what this was about. C++98 does not have `<cstdint` but the C style `stdint.h` was always there.

**Comment by baconpaul** [comment]
It was just about going from `juce::uint8` to `uint8_t` consistently
