### ISSUE TITLE
namespace juce and juce header

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/b-step#12]
Once or in conjunction with #11 kill the juce header and using namespace juce

**Comment by haenkel** [comment]
I'm doing this one tomorrow.

**Comment by baconpaul** [comment]
exciting!

**Comment by baconpaul** [comment]
Oh fyi

```
#ifdef B_STEP_STANDALONE
#include "../../b-step-standalone/JuceLibraryCode/JuceHeader.h"
#else
#include "../JuceLibraryCode/JuceHeader.h"
#endif
```

I'm taking a quick poke at #9 but I'm leaving things like that alone for now so it doesn't conflict with you. Obviously both those branches can go if we follow the #9 strategy which I think will work.
