### ISSUE TITLE
Multi-drag doesn't work / sensitivity is off

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/b-step#22]
Basically set first duration short and RMB drag that knob across the others - some reset but not enough. Console message that we are deleting something. Probably the modified DnD API got mis0-ported.

**Comment by haenkel** [comment]
Is this still happening for you? 
works alright here.

just one mystery left: 
in standalone the "drag-icon" disappears when dragging from left to right
but not when dragging from right to left. 
resetting still works both ways.

**Comment by baconpaul** [comment]
![DragStillBugged](https://user-images.githubusercontent.com/13387561/163733129-39901014-57a1-411b-bcb6-91532862893d.gif)

Sporadically yes. Here's a debug mac build at 82864412593523b9d4f11c3fd7af173475b6aef4

**Comment by baconpaul** [comment]
oh and of course I'm not mouse upping there.And sometimes it doesn't stop as you can see

**Comment by haenkel** [comment]
- The delete message still looks to be in sync with you loosing connection (mac mouse messages different? (broken cable? :) ) 
- Is it the same when dragging from right to left? 

Also no alpha render on linux, where you have transparency i get an opaque square.
![rect](https://user-images.githubusercontent.com/100365267/163734576-6e0fbbc6-8be8-48d6-8ff1-28927c80864e.jpg)

And how does it behave on windows? ( @mthierman could you try the above described? )

**Comment by baconpaul** [comment]
Dragging the other direction it dismisses immediately many but not every time.

![LikeSo](https://user-images.githubusercontent.com/13387561/163736836-08a124b2-bd2e-4993-b03d-7ff583f73ea4.gif)

**Comment by baconpaul** [comment]
<img width="743" alt="Screen Shot 2022-04-17 at 7 55 44 PM" src="https://user-images.githubusercontent.com/13387561/163736865-4f748222-7db9-42f9-8f73-8311a3fd8199.png">

The stack looks like this

**Comment by baconpaul** [comment]
Stopping in the debugger

```
 auto q = getTimerInterval();
    if (getTimerInterval() == GLOBAL_VALUE_HOLDER::getInstance()->LONG_MOUSE_DOWN_INTERVAL ||
        getTimerInterval() == 1)
    {
        is_a_long_mouse_down_event = true;
        _owner->on_long_mouse_down();
    }
    else
        _owner->on_mouse_up(*mouse_up_fake);
```

I see that the timer interval is 1000 and the LONG_HOLD interval is 750. Who knows why?

**Comment by baconpaul** [comment]
Oh had and I know why and I have a fix. Hold on.

**Comment by mthierman** [comment]
> And how does it behave on windows? ( @mthierman could you try the above described? )

Seems to work fine on windows

**Comment by baconpaul** [comment]
This is a mac only thing yeah. Here's the comment from my fixing PR #62

```
The "RMB Drag" gesture on a mac trackpad is two fingers down,
click, drag. Cool. But 2 fingers down can also begin a wheel event.
The mac trackpad is smart enough to not send any motion but it does
generate a zero distance wheel event which B-Step picks up and uses
to interfere with the drag event. So don't start the wheel timer on
a zero distance wheel event.
```
