### ISSUE TITLE
The Scales in the Chord Picker are idiosyncratic

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/b-step#23]
The scales in the chord picker are a bit idiosyncratically selected. Also we don't really call "Hungarian Gypsy" that any more - double harmonic minor is the more standard name.

**Comment by sjaehn** [comment]
And I would say that "Hungarian minor"  (without g*) is more common. Also Wikipedia uses this term.

**Comment by haenkel** [comment]
Hungarian_Minor is already taken so lets go with Double_Harmonic_Minor for now 
to at least get rid of that term.

(I tried to find out whats the difference (if any)
between hungarian and double-harmonic but scales give me headache
and after a while it all sounds like 360-varial-heelflip to me.)
