### ISSUE TITLE
Remove the `#ifdef DEMO` code

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/b-step#24]
since we won't have a demo version any more

**Comment by baconpaul** [comment]
I'm just gonna knock this out quickly now along with the USE_SYNTH stuff in #25

**Comment by baconpaul** [comment]
Actually may change that plan slightly....

**Comment by baconpaul** [comment]
Yeah will clean up some of these as I go but #9 is first focus

**Comment by haenkel** [comment]
I'd remove this now too and remove the "whats new" startup screen with it if there is no objection.

**Comment by baconpaul** [comment]
Yes demo and what’s new can all go too! No objection here
