### ISSUE TITLE
Remove or Restore/Improve the `#ifdef USE_A_SYNTH` code

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/b-step#25]
Probably remove though. Tommy told us that he wrote monique so he would have a synth for B-Step :)

**Comment by haenkel** [comment]
https://drive.google.com/drive/folders/1umaM9a0S52lAqjfbO3S9pWb-D3ys9EZF
Is where the freeware monoplugs are for reference.
No synth parts anywhere in that version so removing them now.
