### ISSUE TITLE
Scoped Pointer Workarounds with .release()

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/b-step#5]
We really need to remove ScopedPointer

but in a bunch of places where JUCE apis had turned to unique I did an assignment with a release()

so revisit all fo them

**Comment by baconpaul** [comment]
```
addAndMakeVisible(label_7 = new Label(String(), TRANS("RECEIVE CC:")));
```    

that pattern (where label_7 is a scoped pointer) is also all over the place. That's the kind of thing you can script out though pretty easily to fix them all with a transform.

**Comment by haenkel** [comment]
I can do some more of these over the week,
but I thought to push them in somewhat smaller bundles.
While it's not hard to replace them
it's also not hard to mess up somewhere in between 
and if that still compiles it'll be unfindable in one large commit.

**Comment by baconpaul** [comment]
Smart! I agree the ability to bisect to a bug is super useful. 

I'm traveling end of week so will be phone only - no plans to commit to b-step in next 5 days.

will probably do clap adapter when i'm back.
