### ISSUE TITLE
License Headers

### ISSUE THREAD

**Issue by haenkel** [surge-synthesizer/b-step#54]
...need to be added.

What's the convention again? only .h, only .cpp or all?

suggestion, taken from SC:
```
/*
** B-Step is Free and Open Source Software
**
** B-Step is made available under the Gnu General Public License, v3.0
** https://www.gnu.org/licenses/gpl-3.0.en.html; The authors of the code
** reserve the right to re-license their contributions under the MIT license in the
** future at the discretion of the project maintainers.
**
** Copyright 2014-2022 by various individuals as described by the git transaction log
**
** All source at: https://github.com/surge-synthesizer/b-step.git
**
** B-Step was a commercial product from 2014-2022, with copyright and ownership
** in that period held by Thomas Arndt at Monoplugs. Thomas made B-Step
** open source in March 2022.
*/
```
Not sure about 2014.

**Comment by baconpaul** [comment]
I don’t know about the 2014 either but otherwise find that perfect. Does kvr have a first release date for bstep?

**Comment by haenkel** [comment]
> but otherwise find that perfect.

well, I mean, you wrote it :)

jan 2014, there it is:
https://www.kvraudio.com/news/monoplugs-releases-b-step-sequencer-for-mac-os-x-windows-and-linux-24526

**Comment by baconpaul** [comment]
> > but otherwise find that perfect.
> 
> well, I mean, you wrote it :)
> 

ha! Well at least I’m consistent :)
