### ISSUE TITLE
Further less important cleanups

### ISSUE THREAD

**Issue by haenkel** [surge-synthesizer/b-step#55]
- All the projucer generated comments ("this is where the headers go", 
  "put your own code here" etc.)
  do we need it?

- Switching to `pragma once` would silence another less important clangd warning 
  (`including_mainfile_in_preamble`)

- CMake format: It's a mix of styles now. 
  Since most of the work there is copy/paste across the repos 
  at this point, let's choose one and document it somewhere 
  (surge dev docs for example).

**Comment by baconpaul** [comment]
Projucer comments can go 
Cmake 2 space format seems to be what we use but welcome whatever standard you want 
Pragma once is kinda not the standard. We sort of use it in surge but I’ve been moving away. No strong feelings there though since it does work in all our compilers

**Comment by haenkel** [comment]
Like the title says none of this is really important. I have no preference for cmake format, as long as its one thing.
2 spaces and no space between if and () like in surge it is then.
Likewise for the header guards, if you are moving away from pragma everywhere else then no need to change it here.
